### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by Ilnicki010** [rlueder/tidytweets#32]
IMO It'd be nice to move all the texts to the separate file they'd be easier to maintain and edit. Right now we can cover English and Polish. Maybe in future other contributors will translate the app to their native languages as well.

https://medium.com/@jishnu61/6-easy-steps-to-localize-your-react-application-internationalization-with-i18next-8de9cc3a66a1

What's your view on that @rlueder?

**Comment by rlueder** [comment]
I think this would be great, I can help translate it into Portuguese (BR), Spanish and German so that'd make it 5 languages out of the box. I haven't spent much time on i18n before but I know that at my company the team responsible for translations uses this package: https://formatjs.io/docs/react-intl/ not sure how it compares to i18next and pros/cons, maybe start there?

**Comment by rlueder** [comment]
Implemented by @juan-colombo95 Thanks!
